pato_homepage:
    pattern:  /
    defaults: { _controller: PatoBundle:Default:index }

#cliente
pato_cliente_homepage:
    pattern: /clientes/
    defaults: { _controller: PatoBundle:Clientes:index }
    methods: [GET]

pato_cliente_post:
    pattern: /cliente
    defaults: { _controller: PatoBundle:Clientes:post, _format: json }
    methods: [POST]

pato_cliente_get:
    pattern: /cliente/{id}
    defaults: { _controller: PatoBundle:Clientes:get, id: 0 }
    methods: [GET]
    requirements:
        id: \d+

pato_cliente_get_view:
    pattern: /cliente/ver/{id}
    defaults: { _controller: PatoBundle:Clientes:ver, id: 0 }
    methods: [GET]
    requirements:
        id: \d+

pato_cliente_page:
    pattern: /clientes/{page}
    defaults: { _controller: PatoBundle:Clientes:page}
    methods: [GET]
    requirements:
        page: \d+

pato_cliente_novo:
    pattern: /clientes/novo
    defaults: { _controller: PatoBundle:Clientes:novo }

pato_cliente_editar:
    pattern: /clientes/editar/{id}
    defaults: { _controller: PatoBundle:Clientes:editar, id: 0 }
    methods: [GET]
    requirements:
        id: \d+

#pais
pato_pais_post:
    pattern: /pais
    defaults: { _controller: PatoBundle:Paises:post }
    methods: [POST]

pato_pais_get:
    pattern: /pais/{id}
    defaults: { _controller: PatoBundle:Paises:get, id: 0 }
    methods: [GET]
    requirements:
        id: \d+

#estado
pato_estado_post:
    pattern: /estado
    defaults: { _controller: PatoBundle:Estados:post }
    methods: [POST]

pato_estado_get:
    pattern: /estado/{id}
    defaults: { _controller: PatoBundle:Estados:get, id:0 }
    methods: [GET]
    requirements:
        id: \d+

pato_estados_por_pais_get:
    pattern: /estados/{pais}
    defaults: { _controller: PatoBundle:Estados:estadosPorPais, pais: 1}
    methods: [GET]
    requirements:
        id: \d+

#cidade
pato_cidade_post:
    pattern: /cidade
    defaults: { _controller: PatoBundle:Cidades:post }
    methods: [POST]

pato_cidade_get:
    pattern: /cidade/{id}
    defaults: { _controller: PatoBundle:Cidades:get, id:0 }
    methods: [GET]
    requirements:
        id: \d+

pato_cidades_por_estado_get:
    pattern: /cidades/{estado}
    defaults: { _controller: PatoBundle:Cidades:cidadesPorEstado, estado: 1 }
    methods: [GET]
    requirements:
        id: \d+

#usuario
pato_usuario_post:
    pattern: /usuario
    defaults: { _controller: PatoBundle:Usuarios:post }
    methods: [POST]

pato_usuario_get:
    pattern: /usuario/{id}
    defaults: { _controller: PatoBundle:Usuarios:get, id:0 }
    methods: [GET]
    requirements:
        id: \d+

#empresas
pato_empresa_homepage:
    pattern: /empresas
    defaults: { _controller: PatoBundle:Empresas:index }
    methods: [GET]

pato_empresa_nova:
    pattern: /empresas/nova
    defaults: { _controller: PatoBundle:Empresas:nova }
    methods: [GET]

pato_empresa_nova_salva:
    pattern: /empresas/nova
    defaults: { _controller: PatoBundle:Empresas:novaSalva }
    methods: [POST]

pato_empresa_ver:
    pattern: /empresas/ver/{id}
    defaults: { _controller: PatoBundle:Empresas:ver, id:0 }
    methods: [GET]
    requirements:
        id: \d+

pato_empresa_editar:
    pattern: /empresas/editar/{id}
    defaults: { _controller: PatoBundle:Empresas:editar }
    methods: [GET]
    requirements:
        id: \d+

pato_empresa_editar_atualizar:
    pattern: /empresas/editar/{id}
    defaults: { _controller: PatoBundle:Empresas:editarAtualizar }
    methods: [POST]
    requirements:
        id: \d+

pato_cidade_get:
    pattern: /empresa/{id}
    defaults: { _controller: PatoBundle:Empresas:get, id:0 }
    methods: [GET]
    requirements:
        id: \d+

pato_cidade_get_search:
    pattern: /empresa/busca/{nome}
    defaults: { _controller: PatoBundle:Empresas:busca, nome:0 }
    methods: [GET]

#caixa
pato_caixa_entrada_post:
    pattern: /caixa/entrada
    defaults: { _controller: PatoBundle:Caixas:entrada }
    methods: [POST]

pato_caixa_movimento_post:
    pattern: /caixa/movimento
    defaults: { _controller: PatoBundle:CaixasMovimentos:movimento }
    methods: [POST]

pato_caixa_movimento_pegar:
    pattern: /caixa/movimento/{id}
    defaults: { _controller: PatoBundle:CaixasMovimentos:pegarMovimento }
    requirements:
        id: \d+

pato_caixa_movimento_deletar:
    pattern: /caixa/movimento/deletar/{id}
    defaults: { _controller: PatoBundle:CaixasMovimentos:deletarMovimento, id: 0 }
    requirements:
        id: \d+

pato_caixa_homepage:
    pattern: /caixa/{caixa}/{ano}/{mes}
    defaults: { _controller: PatoBundle:Caixas:index, caixa: 0, ano:0, mes:0 }
    methods: [GET]
    requirements:
        caixa: \d+
        mes: \d+
        ano: \d+

pato_caixa_tipos_movimentos:
    pattern: /caixa/tiposmovimento/{tipoMovimento}
    defaults: { _controller: PatoBundle:CaixasMovimentosTipos:tiposMovimento, tipoMovimento: 'todos' }
    methods: [GET]

#configuracao
pato_configuracao_homepage:
    pattern: /configuracao
    defaults: { _controller: PatoBundle:Configuracao:index }

pato_configuracao_caixa_index:
    pattern: /configuracao/caixa
    defaults: { _controller: PatoBundle:Caixas:configuracaoCaixaIndex }

pato_configuracao_caixa_index_crud_novo:
    pattern: /configuracao/caixa/novo
    defaults: { _controller: PatoBundle:Caixas:configuracaoCaixaCrudNovo }

pato_configuracao_caixa_index_crud_editar:
    pattern: /configuracao/caixa/editar/{id}
    defaults: { _controller: PatoBundle:Caixas:configuracaoCaixaCrudEditar, id: 0 }
    methods: [GET]
    requirements:
        id: \d+

pato_configuracao_caixa_index_crud_editar_atualizar:
    pattern: /configuracao/caixa/editar/{id}
    defaults: { _controller: PatoBundle:Caixas:configuracaoCaixaCrudEditarAtualizar, id: 0 }
    methods: [POST]
    requirements:
        id: \d+

pato_configuracao_caixa_index_crud_deletar:
    pattern: /configuracao/caixa/deletar/{id}
    defaults: { _controller: PatoBundle:Caixas:configuracaoCaixaCrudDeletar, id: 0 }
    requirements:
        id: \d+
