CloudSource\PatoBundle\Entity\Auditoria:
    type: entity
    table: auditoria
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
    lifecycleCallbacks: {  }
