CloudSource\PatoBundle\Entity\CaixasMovimentosTipos:
    type: entity
    table: caixas_movimentos_tipos
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
        criado:
            type: datetime
            nullable: false
        excluido:
            type: datetime
            nullable: true
        movimentoTipo:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: movimento_tipo
        descricao:
            type: string
            length: 255
            fixed: false
            nullable: true
        tipo:
            type: boolean
            nullable: false
    lifecycleCallbacks: {  }
