CloudSource\PatoBundle\Entity\Cidades:
    type: entity
    table: cidades
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
        cidade:
            type: string
            length: 45
            fixed: false
            nullable: true
    manyToOne:
        estado:
            targetEntity: Estados
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                estado:
                    referencedColumnName: id
            orphanRemoval: false
    uniqueConstraints:
        cidade_estado_idx:
            columns: cidade, estado
    lifecycleCallbacks: {  }
