CloudSource\PatoBundle\Entity\Clientes:
    type: entity
    table: clientes
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
        nome:
            type: string
            length: 255
            fixed: false
            nullable: false
        email:
            type: string
            length: 255
            fixed: false
            nullable: true
        cpf:
            type: string
            length: 11
            fixed: false
            nullable: true
        rg:
            type: string
            length: 20
            fixed: false
            nullable: true
        telefone:
            type: string
            length: 100
            fixed: false
            nullable: true
        celular:
            type: string
            length: 100
            fixed: false
            nullable: true
        endereco:
            type: string
            length: 255
            fixed: false
            nullable: true
        enderecoComplemento:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: endereco_complemento
        bairro:
            type: string
            length: 45
            fixed: false
            nullable: true
        descricao:
            type: string
            length: 255
            fixed: false
            nullable: true
        criado:
            type: datetime
            nullable: false
        excluido:
            type: datetime
            nullable: true
        atualizado:
            type: datetime
            nullable: true
    manyToOne:
        cidade:
            targetEntity: Cidades
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                cidade:
                    referencedColumnName: id
            orphanRemoval: false
        clientesTipos:
            targetEntity: ClientesTipos
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                clientes_tipos_id:
                    referencedColumnName: id
            orphanRemoval: false
        criador:
            targetEntity: Usuarios
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                criador:
                    referencedColumnName: id
            orphanRemoval: false
        empresa:
            targetEntity: Empresas
            cascade: {  }
            mappedBy: null
            inversedBy: empregados
            joinColumns:
                empresa:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
