CloudSource\PatoBundle\Entity\Empresas:
    type: entity
    table: empresas
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
        criado:
            type: datetime
            nullable: false
        excluido:
            type: datetime
            nullable: true
        atualizado:
            type: datetime
            nullable: true
        razaoSocial:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: razao_social
        nomeFantasia:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: nome_fantasia
        cnpj:
            type: string
            length: 20
            fixed: false
            nullable: true
        email:
            type: string
            length: 255
            fixed: false
            nullable: true
        site:
            type: string
            length: 255
            fixed: false
            nullable: true
        endereco:
            type: string
            length: 255
            fixed: false
            nullable: true
        enderecoComplemento:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: endereco_complemento
        bairro:
            type: string
            length: 45
            fixed: false
            nullable: true
    oneToMany:
        empregados:
            targetEntity: Clientes
            mappedBy: empresa
    manyToOne:
        cidade:
            targetEntity: Cidades
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                cidade:
                    referencedColumnName: id
            orphanRemoval: false
        criador:
            targetEntity: Usuarios
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                criador:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
