CloudSource\PatoBundle\Entity\Oportunidades:
    type: entity
    table: oportunidades
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
    lifecycleCallbacks: {  }
