CloudSource\PatoBundle\Entity\Paises:
    type: entity
    table: paises
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
        pais:
            type: string
            length: 100
            fixed: false
            nullable: true
            unique: true
    lifecycleCallbacks: {  }
